import Mathlib.Analysis.Calculus.Deriv.Basic
import Mathlib.Analysis.SpecialFunctions.Pow.Real
import Mathlib.Analysis.SpecialFunctions.Pow.Deriv

/-!
# Butcher §101 — The Kepler problem

This file collects the entities of subsection 101 of Butcher's
*Numerical Methods for Ordinary Differential Equations* (3rd ed.).

So far this file contains Theorem 101A (conservation of the Hamiltonian
and angular momentum along Kepler trajectories), formalised as the two
derivative-vanishing theorems `kepler_H_const` and `kepler_A_const`.

The proofs of `kepler_H_const` and `kepler_A_const` were generated by the
Aristotle automated theorem prover.
-/

namespace OpenMath.Chapter1.Section101

/-- Butcher §101, equations (101a)–(101d) packaged as a hypothesis bundle.

The four scalar functions `y₁, y₂, y₃, y₄ : ℝ → ℝ` represent the position
and velocity components of a scaled two-body problem (γM = 1). The
`nonzero` field excludes the singularity at the origin, where the
potential `(y₁² + y₂²)^(-1/2)` is undefined. -/
structure KeplerSystem (y₁ y₂ y₃ y₄ : ℝ → ℝ) : Prop where
  d_y₁ : ∀ x, HasDerivAt y₁ (y₃ x) x
  d_y₂ : ∀ x, HasDerivAt y₂ (y₄ x) x
  d_y₃ : ∀ x, HasDerivAt y₃
              (- y₁ x / (y₁ x ^ 2 + y₂ x ^ 2) ^ ((3 : ℝ) / 2)) x
  d_y₄ : ∀ x, HasDerivAt y₄
              (- y₂ x / (y₁ x ^ 2 + y₂ x ^ 2) ^ ((3 : ℝ) / 2)) x
  nonzero : ∀ x, y₁ x ^ 2 + y₂ x ^ 2 ≠ 0

/-- Butcher §101 — Hamiltonian (total energy) of the Kepler problem.

`H = (1/2)(y₃² + y₄²) - (y₁² + y₂²)^(-1/2)`. The kinetic-energy term is
elementary; the potential term uses `Real.rpow` and so `kepler_H` is
`noncomputable`. -/
noncomputable def kepler_H (y₁ y₂ y₃ y₄ : ℝ → ℝ) (x : ℝ) : ℝ :=
  (1 / 2) * (y₃ x ^ 2 + y₄ x ^ 2)
    - (y₁ x ^ 2 + y₂ x ^ 2) ^ (-(1 : ℝ) / 2)

/-- Butcher §101 — Angular momentum of the Kepler problem.

`A = y₁ y₄ - y₂ y₃`. -/
def kepler_A (y₁ y₂ y₃ y₄ : ℝ → ℝ) (x : ℝ) : ℝ :=
  y₁ x * y₄ x - y₂ x * y₃ x

/-- Butcher §101, Theorem 101A (part 1) — *the Hamiltonian is constant*.

The Hamiltonian `kepler_H` is constant along solutions of the Kepler ODE,
i.e. its derivative vanishes everywhere. -/
theorem kepler_H_const {y₁ y₂ y₃ y₄ : ℝ → ℝ}
    (h : KeplerSystem y₁ y₂ y₃ y₄) :
    ∀ x, HasDerivAt (kepler_H y₁ y₂ y₃ y₄) 0 x := by
  intro x
  have h_deriv_y1 : HasDerivAt y₁ (y₃ x) x := h.d_y₁ x
  have h_deriv_y2 : HasDerivAt y₂ (y₄ x) x := h.d_y₂ x
  have h_deriv_y3 : HasDerivAt y₃ (- y₁ x / (y₁ x ^ 2 + y₂ x ^ 2) ^ ((3 : ℝ) / 2)) x := h.d_y₃ x
  have h_deriv_y4 : HasDerivAt y₄ (- y₂ x / (y₁ x ^ 2 + y₂ x ^ 2) ^ ((3 : ℝ) / 2)) x := h.d_y₄ x;
  convert HasDerivAt.sub ( HasDerivAt.const_mul ( 1 / 2 : ℝ ) ( HasDerivAt.add ( h_deriv_y3.pow 2 ) ( h_deriv_y4.pow 2 ) ) ) ( HasDerivAt.rpow_const ( h_deriv_y1.pow 2 |> HasDerivAt.add <| h_deriv_y2.pow 2 ) _ ) using 1 <;> norm_num;
  · rw [ Real.rpow_neg ( by positivity ) ] ; ring;
  · exact h.nonzero x

/-- Butcher §101, Theorem 101A (part 2) — *angular momentum is constant*.

The angular momentum `kepler_A` is constant along solutions of the Kepler
ODE, i.e. its derivative vanishes everywhere. -/
theorem kepler_A_const {y₁ y₂ y₃ y₄ : ℝ → ℝ}
    (h : KeplerSystem y₁ y₂ y₃ y₄) :
    ∀ x, HasDerivAt (kepler_A y₁ y₂ y₃ y₄) 0 x := by
  intro x
  obtain ⟨h1, h2, h3, h4⟩ := h;
  convert HasDerivAt.sub ( HasDerivAt.mul ( h1 x ) ( h4 x ) ) ( HasDerivAt.mul ( h2 x ) ( h3 x ) ) using 1 ; ring

end OpenMath.Chapter1.Section101