import Mathlib.Analysis.Calculus.Deriv.Basic
import Mathlib.Analysis.Calculus.Deriv.Mul
import Mathlib.Analysis.Calculus.Deriv.Add

/-!
# Butcher §123 — Further Hamiltonian problems

This file collects the entities of subsection 123 of Butcher's
*Numerical Methods for Ordinary Differential Equations* (3rd ed.).

So far this file contains Theorem 123B (area invariance of the symplectic
form `uᵀ J v` on perturbations of a two-dimensional Hamiltonian
trajectory), formalised as `area_const`.
-/

namespace OpenMath.Chapter1.Section123

/-- Butcher §123, the variational system for a two-dimensional
Hamiltonian problem.

`(u₁, u₂)` and `(v₁, v₂)` are perturbations to a trajectory `y` of a
2-D Hamiltonian system; both evolve under the same Hessian `W = Hess H`
of the Hamiltonian. We abstract the four entries of `W` as scalar
functions `W₁₁, W₁₂, W₂₂ : ℝ → ℝ`, with the off-diagonal entry `W₁₂`
shared between positions `(1,2)` and `(2,1)` because the Hessian of a
smooth `H` is symmetric.

Expanding `v' = J W v` with `J = [[0, -1], [1, 0]]` gives the four
component ODEs below. -/
structure HamiltonianVar2D
    (u₁ u₂ v₁ v₂ W₁₁ W₁₂ W₂₂ : ℝ → ℝ) : Prop where
  d_u₁ : ∀ x, HasDerivAt u₁ (-(W₁₂ x * u₁ x + W₂₂ x * u₂ x)) x
  d_u₂ : ∀ x, HasDerivAt u₂ ( W₁₁ x * u₁ x + W₁₂ x * u₂ x) x
  d_v₁ : ∀ x, HasDerivAt v₁ (-(W₁₂ x * v₁ x + W₂₂ x * v₂ x)) x
  d_v₂ : ∀ x, HasDerivAt v₂ ( W₁₁ x * v₁ x + W₁₂ x * v₂ x) x

/-- Butcher §123 — symplectic area form on ℝ².

`uᵀ J v = u₁ v₂ - u₂ v₁` for the standard symplectic matrix
`J = [[0, -1], [1, 0]]`. -/
def area (u₁ u₂ v₁ v₂ : ℝ → ℝ) (x : ℝ) : ℝ :=
  u₁ x * v₂ x - u₂ x * v₁ x

/-- Butcher §123, Theorem 123B — *area is invariant*.

The symplectic form `u₁ v₂ - u₂ v₁` of two perturbations of a 2-D
Hamiltonian trajectory has zero derivative everywhere.

The proof of `area_const` was generated by the Aristotle automated
theorem prover. -/
theorem area_const
    {u₁ u₂ v₁ v₂ W₁₁ W₁₂ W₂₂ : ℝ → ℝ}
    (h : HamiltonianVar2D u₁ u₂ v₁ v₂ W₁₁ W₁₂ W₂₂) :
    ∀ x, HasDerivAt (area u₁ u₂ v₁ v₂) 0 x := by
  unfold area
  intro x
  have h_du := (h.d_u₁ x).mul (h.d_v₂ x)
  have h_dv := (h.d_u₂ x).mul (h.d_v₁ x)
  convert (h_du.sub h_dv) using 1
  ring

end OpenMath.Chapter1.Section123
